// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: apis.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DBApisService_StoreFoldersInfo_FullMethodName = "/protos.DBApisService/StoreFoldersInfo"
)

// DBApisServiceClient is the client API for DBApisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 폴더 정보 저장 서비스를 정의합니다.
type DBApisServiceClient interface {
	// 아무 입력 값 없이 서버 내부의 폴더 정보를 DB에 저장합니다.
	StoreFoldersInfo(ctx context.Context, in *StoreFoldersInfoRequest, opts ...grpc.CallOption) (*StoreFoldersInfoResponse, error)
}

type dBApisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDBApisServiceClient(cc grpc.ClientConnInterface) DBApisServiceClient {
	return &dBApisServiceClient{cc}
}

func (c *dBApisServiceClient) StoreFoldersInfo(ctx context.Context, in *StoreFoldersInfoRequest, opts ...grpc.CallOption) (*StoreFoldersInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreFoldersInfoResponse)
	err := c.cc.Invoke(ctx, DBApisService_StoreFoldersInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBApisServiceServer is the server API for DBApisService service.
// All implementations must embed UnimplementedDBApisServiceServer
// for forward compatibility.
//
// 폴더 정보 저장 서비스를 정의합니다.
type DBApisServiceServer interface {
	// 아무 입력 값 없이 서버 내부의 폴더 정보를 DB에 저장합니다.
	StoreFoldersInfo(context.Context, *StoreFoldersInfoRequest) (*StoreFoldersInfoResponse, error)
	mustEmbedUnimplementedDBApisServiceServer()
}

// UnimplementedDBApisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDBApisServiceServer struct{}

func (UnimplementedDBApisServiceServer) StoreFoldersInfo(context.Context, *StoreFoldersInfoRequest) (*StoreFoldersInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreFoldersInfo not implemented")
}
func (UnimplementedDBApisServiceServer) mustEmbedUnimplementedDBApisServiceServer() {}
func (UnimplementedDBApisServiceServer) testEmbeddedByValue()                       {}

// UnsafeDBApisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DBApisServiceServer will
// result in compilation errors.
type UnsafeDBApisServiceServer interface {
	mustEmbedUnimplementedDBApisServiceServer()
}

func RegisterDBApisServiceServer(s grpc.ServiceRegistrar, srv DBApisServiceServer) {
	// If the following call pancis, it indicates UnimplementedDBApisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DBApisService_ServiceDesc, srv)
}

func _DBApisService_StoreFoldersInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreFoldersInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBApisServiceServer).StoreFoldersInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBApisService_StoreFoldersInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBApisServiceServer).StoreFoldersInfo(ctx, req.(*StoreFoldersInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DBApisService_ServiceDesc is the grpc.ServiceDesc for DBApisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DBApisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.DBApisService",
	HandlerType: (*DBApisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreFoldersInfo",
			Handler:    _DBApisService_StoreFoldersInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apis.proto",
}
